export const USAGE_HEARTBEAT_INTERVAL_MS = Number(process.env.NEXT_PUBLIC_USAGE_HEARTBEAT_INTERVAL_MS) || 45_000;
export const USAGE_INACTIVITY_THRESHOLD_MS = Number(process.env.NEXT_PUBLIC_USAGE_INACTIVITY_THRESHOLD_MS) || 5 * 60 * 1000;
